// data points for knn
var data = [
{rooms :  1, area :	 350, type : 'apartment', distance : null},
{rooms :  2, area :  300, type : 'apartment', distance : null},
{rooms :  3, area :  300, type : 'apartment', distance : null},
{rooms :  4, area :  250, type : 'apartment', distance : null},
{rooms :  4, area :  500, type : 'apartment', distance : null},
{rooms :  4, area :  400, type : 'apartment', distance : null},
{rooms :  5, area :  450, type : 'apartment', distance : null},
{rooms :  7, area :  850, type : 'house',	  distance : null},
{rooms :  7, area :  900, type : 'house',	  distance : null},
{rooms :  7, area : 1200, type : 'house',	  distance : null},
{rooms :  8, area : 1500, type : 'house',	  distance : null},
{rooms :  9, area : 1300, type : 'house',	  distance : null},
{rooms :  8, area : 1240, type : 'house',	  distance : null},
{rooms : 10, area : 1700, type : 'house',	  distance : null},
{rooms :  9, area : 1000, type : 'house',	  distance : null},
{rooms :  1, area :  800, type : 'flat',	  distance : null},
{rooms :  3, area :  900, type : 'flat',	  distance : null},
{rooms :  2, area :  700, type : 'flat', 	  distance : null},
{rooms :  1, area :  900, type : 'flat',	  distance : null},
{rooms :  2, area : 1150, type : 'flat',	  distance : null},
{rooms :  1, area : 1000, type : 'flat',	  distance : null},
{rooms :  2, area : 1200, type : 'flat',	  distance : null},
{rooms :  1, area :	1300, type : 'flat',	  distance : null}
];
